version: "3.8"

services:

  api:
    build: .
    command: python main.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ./.env
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: